### ISSUE TITLE
Window and Shutter feature request

### ISSUE THREAD

**Issue by Q7Jensen** [ioBroker/ioBroker.vis-hqwidgets#10]
Erweiterung des Widgets Window and Shutter für Raffstores. Zusätzliche ObjectID für Winkelstellung, Bedienung und Visualisierung des Winkels der Lamellen.

Extension of the Widget Window and Shutter for Venetian blinds. Additional ObjectID for angular positioning, operation and visualization of the angle of the slats.

**Comment by KingAndi** [comment]
Genau das such ich auch! Wundert mich nur dass dies kaum wer braucht...
