### ISSUE TITLE
Shutter für Steuerung und Anzeige 2 verschieden Datenpunkte

### ISSUE THREAD

**Issue by innriver** [ioBroker/ioBroker.vis-hqwidgets#18]
Ist es möglich, für den Rollladen für die Steuerung einen anderen Datenpunkt als für den aktuellen Status zu verwenden. Grund sind die Rollladenaktoren HmiP BROLL und HmiP FROLL von Homematic. Die haben für die aktuelle Höhe der Rollläden und für die Steuerung verschiedene Kanäle und die Anzeige am gesteuerten Kanal entspricht nicht immer dem aktuellen Stand, vor allem dann, wenn mit Tastern gesteuert wird.

Grüße und gesund bleiben

**Comment by tiff1112** [comment]
siehe #17 gleiche Anfrage, anderes protokoll, sollte aber egal sein ob homematic oder KNX

Grüße!
