### ISSUE TITLE
Laden der Schrift über fonts.googleapis.com

### ISSUE THREAD

**Issue by jack-blackson** [ioBroker/ioBroker.vis-hqwidgets#19]
Hallo!

Ich hatte das Problem, das wenn bei mir das Internet ausfällt, auch die VIS am Tablet nicht mehr funktioniert hat. Nach längerem forschen war das Problem dieser Adapter - der jedes mal die Schriften frisch von Google lädt. Meinst du, es wäre möglich, die Schrift direkt in den Adapter einzubauen? Das würde dieses Problem glaub beheben. Nachdem ich den Adapter testhalber deinstalliert habe, war bei mir die VIS ohne Internet kein Problem mehr.

**Comment by Wildbill-Z** [comment]
Workaround für diejenigen die pihole am Laufen haben oder etwas Ähnliches:
fonts.googleapis.com und fonts.gstatic.com nach 0.0.0.0 (NXDOMAIN) auflösen. Dann wird sofort weitergeladen. [Siehe Forumsthread hier](https://forum.iobroker.net/topic/32757/gel%C3%B6st-vis-probleme-wenn-internetverbindung-fehlt)

Gruss, Jürgen

**Comment by Omega236** [comment]
Hatte heute das gleiche Problem. Wäre super wenn das behoben wird
