### ISSUE TITLE
unwanted action with mouse-over

### ISSUE THREAD

**Issue by MrLee99** [ioBroker/ioBroker.vis-hqwidgets#24]
hqwidgets on/off as a push-bottun (Taster)
on mouse-over the widgets trigger like they should on mouse click

Behavior is only with Microsoft Edge not with Firefox.

Versions:
hqwidgets style Widgets 1.1.5
vis  1.2.11

edge  85.0.564.41 (Offizielles Build) (64-Bit)

Thanks
Mr.Lee

**Comment by pustelbaer** [comment]
I have same issue with firefox and hqwidgets on/off. Sometimes the widget triggers the action (Taster) as it should only happen by mouse click.

**Comment by AxelHoss** [comment]
i have the same behavior on FireFox. Is there a solution?

**Comment by heymkeyu** [comment]
Same here 
* Chrome (Windows)
* FullyKiosk (Android, couldn't quite figure out how the acttion was triggered, maybe upon reload)

This can be extremely ugly if the unwanted action triggered opens up a door by mistake (KeyMatic or similar).
