### ISSUE TITLE
bool.button doesn't work properly on touch screens

### ISSUE THREAD

**Issue by mswiege** [ioBroker/ioBroker.vis-hqwidgets#25]
The bool button on/off always immediately resets the value if the button is clicked on a touchscreen. It seems to interpret a press on a touchscreen as two clicks and therefore sets to true and immediately back to false.

Tested on a touchscreen running raspbian and chromium

Side note: The "Basic bub on/off" doesn't have this issue

**Comment by mswiege** [comment]
issue still exists

**Comment by willi5** [comment]
Das Problem besteht schon seit Monaten und immer noch. Gibt es Hoffnung?

Viele Grüsse
