### ISSUE TITLE
Widget "Window and Shutter" neues Feature "Fensterkontakt invertieren"

### ISSUE THREAD

**Issue by uelpenich** [ioBroker/ioBroker.vis-hqwidgets#35]
### Neues Feature "Fensterkontakt invertieren" zum Widget "Window and Shutter" 
Im Widget "Window and Shutter" ist zur Zeit die Darstellung von Fenster offen <-> Fenster geschlossen fest an das Signal des Fensterkontaktes mit **offen = true; geschlossen = false** verbunden. Das ist die Arbeitsweise von vielen Nachrüst-Funk-Fenster Kontakten. 
Die Fensterkontakte aus dem Bereich Alarmanlagen arbeiten genau umgekehrt mit **offen = false; geschlossen = true**.

**Meine Bitte:**
Erweitern des Widgets "Window and Shutter" mit der Möglichkeit, den Fensterblattsensor sowie den Griffsensor zu invertieren. 
(Bemerkung: beim Widget "Door" kann der Türkontakt invertiert werden)

**möglicher Workaround 2**: Invertieren des Fenster Signals beim Einlesen. Möchte ich **nicht** anwenden, da bei der Verwendung von MDX KNX Rolladen Aktoren mit Binäreingangen die erweiterten Funktionen (z.B. Schutz vor Aussperren) dann nicht mehr möglich sind.

**Comment by uelpenich** [comment]
**Weitere Möglichkeit**: true und false könnte man über eine JavaScript Funktion im Zusammenhang mit "Binding of objects" vertauschen. Das funtioniert bei dem Parameter "Fensterblatt-Sensor" nicht (wohl aber bei anderen Parametern, die eine Textausgabe zur Folge haben). 
**Frage**: kann man das Widget so erweitern, dass bei allen Parametern "Binding of objects" möglich ist?

**Comment by uelpenich** [comment]
### Brauchbarer Workaround zum "Fensterkontakt invertieren" im Widget "Window and Shutter"
Ich habe für mich eine brauchbare Lösung gefunden, Fensterkontakte aus dem Bereich der Alarmanlagen mit der Arbeitsweise **Fenster offen = false; Fenster geschlossen = true** richtig mit dem Widget "Window and Shutter" zu visalisieren. 
Folgende Änderung habe ich an hqwidgets.js (version 1.1.7) im Verzeichnis _/opt/iobroker/iobroker-data/files/vis/widgets/hqwidgets/js_ gemacht:
**Zeilen 1816 .. 1818 im Original**:
_if ((slidePos == 1 || slidePos === true   || slidePos === 'true' || slidePos === 'open' || slidePos === 'opened') && options.type) {
                div4 +=' hq-blind-blind4-opened-' + options.type;
}_

**Zeilen 1816 .. 1818 abgeändert für Fenster geschlossen = true**:
_if ((slidePos == **0** || slidePos === **false**   || slidePos === '**false**' || slidePos === 'open' || slidePos === 'opened') && options.type) {
                div4 +=' hq-blind-blind4-opened-' + options.type;
}_

Ich habe das System neu gebootet, um die Änderung wirksam zu machen.

**Comment by uelpenich** [comment]
### Doch keine Lösung?
Kurze Zeit nach dem ich _hqwidgets.js_ wie oben beschrieben geändert habe, wird das Programm wieder mit dem Original überschrieben. 
Was habe ich übersehen? Wer schreibt das Original zurück? Was muss ich anders machen?
Danke für Eure Hinweise.

**Comment by uelpenich** [comment]
Sie haben recht, die Invertierung eines Eingangssignals gehört in den Geräte- oder Alias Adapter. 
Leider ist der Gerätemanager noch nicht zusammenhängen dokumentiert.

**Comment by uelpenich** [comment]
Wir sind immer noch im "Bananenstecker Zeitalter", wo die Signale mit einzeln gesteckten Kabeln von A nach B und B nach A transportiert werden. ioBroker und der KNX Adapter bieten schon den Vorteil, dass sie mit Zweipoligen Kabeln und Steckern das Steuersignal und die Rückmeldung zusammenfassen können. Über komplizertere Dinge wie Dimmer, RGBW, Heizkessel, . . ., wo mehrere Signalpaare von unterschiedlichen Typen zusammen gehören, wird noch nachgedacht und diskutiert. Da sind die Sprachassistenten schon weiter und definieren "Skills".  

Es wird ein sauberes Ebenen Modell benötigt: Signalerfassung, Signalverarbeitung und Verknüpfung, Geräte Definitionen und Präsentation. Es kann nicht sein, dass die Signalverarbeitung und Verknüpfung in der Visualisierungsebene abgewickelt wird. 
Überall blickt die Hardware durch, für das ioBroker einmal entwickelt wurde. 

. . .  wird alles nur durch kompliziertes umwandeln in zig Skripten möglich . . . 
=> ich bin weitgehend ohne Skripte ausgekommen. Sie erledigen die Signalverarbeitung, bilden aber keine Geräte ab. Damit wird es unübersichtlich. 
Etwas anderes sind Skripte für Zeit- und Ablaufsteuerungen. 
Meine Skripte fahren die Rolladen in Abhängigkeit von Sonnenauf- und -untergang, übertragen die 1wire Temperaturwerte ins KNX System und übertragen die KNX Taster Befehle über FHEM auf Baushaus Funksteckdosen (weil FHEM über SIGNALduino besser mit den unterschiedlichen Funkprotokollen zurecht kommt). 
Signalverarbeitung im Sinne von Umrechnungen mache ich über "linkeddevices". Schade dass linkeddevices jeweils nur ein Eingangssignal kann. Weitere Eingangssignale über die Bindings Syntax wären eine schöne Sache.

**Comment by uelpenich** [comment]
Das Problem hat sich erledigt mit der **vis-2-beta**. 
Der Wert des Griff Sensors lässt sich mit einem vorangestellten **!** invertiren
![grafik](https://github.com/ioBroker/ioBroker.vis-hqwidgets/assets/63613798/4abe50da-e9b8-4e6e-9947-9d236c4fe086)

**Comment by Basti17683** [comment]
Danke für die INfo! Werd gleich mal sehen wie ich die Beta Vis installiere und probier das aus.
Danke :)
