### ISSUE TITLE
widgets werden unvollständig geladen

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.vis-hqwidgets#4]
System: Windows 10 build 1703 x86, 4 GB RAM
frische Installation mit node v6.10.3, ohne icon-sets 
js-controller: 1.0.0
VIS v0.14.2
hqwidgets 1.0.8

widgets im Auswahlframe werden ohne Icons angezeigt
nach der Platzierung auf der View "sind sie verschwunden"
keine Fehlermeldung oder Logeinträge

Trifft mich nicht so hart (Testinstallation), aber wenn neue Nutzer auch auf den Fehler laufen, nicht so schön

**Comment by GermanBluefox** [comment]
einfach
 iobroker restart vis
iobroker u vis

eingeben
