### ISSUE TITLE
Verzeichnispfand unter Windows wurde nicht gefunden

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.vis-hqwidgets#44]
Ich habe eben das Update auf die Version 1.3.0 durchgeführt. Trotz der Nachfolgenden Meldungen, wurde der Versionsstand auf 1.3.0 angehoben, obwohl die Meldung ja suggeriert, das nichts geändert wurde.

 iobroker INFO: Directory "C:/iobroker/GLT/node_modules/iobroker.vis-hqwidgets/www" was not found! Nothing was uploaded or deleted.`

ioB läuft auf einem Windows Betribesystem

`<html>
<body>

host.GLT(GLT) | 2022-08-18 10:57:39.556 | error | cannot check file: C:\iobroker\GLT\log\iobroker.2022-08-11.log - EPERM: operation not permitted, lstat 'C:\iobroker\GLT\log\iobroker.2022-08-11.log'
-- | -- | -- | --
host.GLTGLT) | 2022-08-18 10:57:39.556 | error | host.GLT(GLT) cannot check file: C:\iobroker\GLT\log\iobroker.2022-08-11.log - EPERM: operation not permitted, lstat 'C:\iobroker\GLT\log\iobroker.2022-08-11.log'
host.GLTGLT) | 2022-08-18 10:57:36.961 | info | host.GLT(GLT) instance system.adapter.vis.0 terminated while should be started once
vis.0 | 2022-08-18 10:57:36.193 | info | Terminated (NO_ERROR): Without reason
mqtt.0 | 2022-08-18 10:57:35.323 | info | Client [Poolsteuerung] connection closed: timeout
vis.0 | 2022-08-18 10:57:32.724 | info | vis license is OK.
vis.0 | 2022-08-18 10:57:32.276 | info | starting. Version 1.4.15 in C:/iobroker/GLT/node_modules/iobroker.vis, node: v14.16.0, js-controller: 4.0.23
host.GLTGLT) | 2022-08-18 10:57:28.661 | info | host.GLT(GLT) iobroker exit 0
host.GLTGLT) | 2022-08-18 10:57:27.468 | info | host.GLT(GLT) iobroker upload [0] vis-hqwidgets.admin C:/iobroker/GLT/node_modules/iobroker.vis-hqwidgets/admin/index.html index.html text/html
host.GLTGLT) | 2022-08-18 10:57:27.182 | info | host.GLT(GLT) iobroker upload [1] vis-hqwidgets.admin C:/iobroker/GLT/node_modules/iobroker.vis-hqwidgets/admin/hqwidgets.png hqwidgets.png image/png
host.GLTGLT) | 2022-08-18 10:57:26.949 | info | host.GLT(GLT) iobroker Update "system.adapter.vis-hqwidgets.0"
host.GLTGLT) | 2022-08-18 10:57:25.902 | info | host.GLT(GLT) iobroker Adapter "system.adapter.vis.0" restarted.
host.GLTGLT) | 2022-08-18 10:57:25.794 | info | host.GLT(GLT) "system.adapter.vis.0" enabled
host.GLTGLT) | 2022-08-18 10:57:25.648 | info | host.GLT(GLT) "system.adapter.vis.0" disabled
host.GLTGLT) | 2022-08-18 10:57:25.523 | info | host.GLT(GLT) iobroker INFO: Directory "C:/iobroker/GLT/node_modules/iobroker.vis-hqwidgets/www" was not found! Nothing was uploaded or deleted.
host.GLTGLT) | 2022-08-18 10:57:25.348 | info | host.GLT(GLT) iobroker run `npm audit fix` to fix them, or `npm audit` for details
host.GLTGLT) | 2022-08-18 10:57:25.347 | info | host.GLT(GLT) iobroker found 166 vulnerabilities (17 low, 50 moderate, 79 high, 20 critical)
host.GLTGLT) | 2022-08-18 10:57:25.339 | info | host.GLT(GLT) iobroker 161 packages are looking for funding run `npm fund` for details
host.GLTGLT) | 2022-08-18 10:57:25.338 | info | host.GLT(GLT) iobroker
host.GLTGLT) | 2022-08-18 10:57:20.372 | info | host.GLT(GLT) iobroker + iobroker.vis-hqwidgets@1.3.0 removed 4 packages, updated 1 package and audited 2479 packages in 62.252s
host.GLTGLT) | 2022-08-18 10:57:20.369 | info | host.GLT(GLT) iobroker npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
host.GLTGLT) | 2022-08-18 10:57:20.368 | info | host.GLT(GLT) iobroker npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.8 (node_modules\osx-temperature-sensor):
host.GLTGLT) | 2022-08-18 10:57:20.320 | info | host.GLT(GLT) iobroker npm WARN jscs-loader@0.3.0 requires a peer of jscs@^3.0.3 but none is installed. You must install peer dependencies yourself.
host.GLTGLT) | 2022-08-18 10:57:20.289 | info | host.GLT(GLT) iobroker npm WARN crc@4.1.1 requires a peer of buffer@>=6.0.3 but none is installed. You must install peer dependencies yourself.

</body>
</html>`

**Comment by Apollon77** [comment]
DIe INFO message ist nur eine INFO ... also alles ok ... oder was genau geht nicht? Naja die Meldung suggeriert das einnSchritt nichts zu tun hatte ... sind ein paar mehr :-)
