### ISSUE TITLE
update failing

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.vis-hqwidgets#45]
keeps complaining about non-empty directories .. but there seem to be many .. done some renaming like instructed .. but don't know when it will ever stop.

**Comment by Apollon77** [comment]
this is an NPM issue and not from adapter. Check in iobroker Forum, there is a "one liner" that removes all affected directories.
We still do not know when npm do not delete his opwn temporary stuff :-(

**Comment by Apollon77** [comment]
Sorry gerade unterwegs und habe den daher nicht

**Comment by daniel-lo** [comment]
finde auch nichts .. falls du ihn nachher zur hand hast wäre es sicher gut ihn auch hier zu posten.

**Comment by daniel-lo** [comment]
@Apollon77 

Kann leider grad einige Adapter nicht installieren .. gibt auf welche NPM muss ich zurück gehen damit ich wieder Ruhe habe?

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/57337/fehler-24-bei-adapter-install-update-mit-npm8

**Comment by daniel-lo** [comment]
Super .. vielen Dank .. ging erst nach neustart .. aber ging dann :-)

**Comment by daniel-lo** [comment]
@Apollon77 

Obwohl ich nach dem Befehl alle Updates durchbekommen habe .. passiert es nun erneut:

$ ./iobroker upgrade node-red
Update node-red from @3.3.1 to @4.0.0
NPM version: 8.15.0
Installing iobroker.node-red@4.0.0... (System call)
ERROR: host.iobroker Cannot install iobroker.node-red@4.0.0: 217
ERROR: process exited with code 25

**Comment by Apollon77** [comment]
tja ... lösunfg die gleiche ... Wenn du rausfindest nach welcher aktion diese komisches temp directories liegen bleiben und/oder nachstellen kannst sagen bitte

**Comment by daniel-lo** [comment]
Hilft das schon weiter .. oder tiefer?

$ iobroker upgrade node-red@4.0.0 --debug

Update node-red from @3.3.1 to @4.0.0

NPM version: 8.15.0

Installing iobroker.node-red@4.0.0... (System call)

npm ERR! code ENOTEMPTYnpm ERR! syscall renamenpm ERR! path /opt/iobroker/node_modules/acornnpm ERR! dest /opt/iobroker/node_modules/.acorn-zHERliMHnpm ERR! errno -39

npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/acorn' -> '/opt/iobroker/node_modules/.acorn-zHERliMH'

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2022-08-24T05_31_14_425Z-debug-0.log

host.iobroker Cannot install iobroker.node-red@4.0.0: 217

ERROR: Process exited with code 25

**Comment by daniel-lo** [comment]
@Apollon77 

[2022-08-24T05_31_14_425Z-debug-0.zip](https://github.com/ioBroker/ioBroker.vis-hqwidgets/files/9413141/2022-08-24T05_31_14_425Z-debug-0.zip)

**Comment by Apollon77** [comment]
naja wenn dieses update meckert ... muss an sich etwas was DAVOR war die Ursache sein (weil zum update ists ja schon da). Frage ist also : Was war davor ;-) aber macht wenig sinn jetzt hoer separat zu iterieren ... Haben Forum thread dafür https://forum.iobroker.net/post/846374

**Comment by daniel-lo** [comment]
Man muss den Befehl vor jeder Adapter-Installation ausführen.
Node-Red ist ein besonderer Fall .. dafür erst alle Node-Red Verzeichnisse löschen und dann den Befehl ausführen.

Der Befehl:
cd /opt/iobroker/node_modules
for i in $(find -type d -iname ".*-????????" ! -iname ".local-chromium"); do rm -rf ${i%%/}; done
